[workspace]
members = [ 
    "crates/predict-otron-9000",
    "crates/inference-engine",
    "crates/embeddings-engine",
    "crates/leptos-chat"
]
default-members = ["crates/predict-otron-9000"]
resolver = "2"



[[workspace.metadata.leptos]]
# project name
name = "leptos-project"
bin-package = "leptos-chat"
lib-package = "leptos-chat"